name: Auto-close issues

on:
  issues:
    types: [labeled]

jobs:
  auto-close:
    runs-on: ubuntu-latest

    steps:
    - name: Close issue
      uses: actions/github-script@v6
      with:
        script: 
          if (github.event.label.name === 'completed' || github.event.label.name === 'wontfix') {
            github.rest.issues.update({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: github.event.issue.number,
              state: 'closed'
            });
          }
